package jx.demo.mvc.views;

import jx.demo.mvc.controllers.PersonListController;

public class PersonListPanel extends javax.swing.JPanel {

  public PersonListController controller;

  public PersonListPanel() {
    controller = new PersonListController();
    initComponents();
    controller.setView(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    personTablePopup = new javax.swing.JPopupMenu();
    editPersonMenuItem = new javax.swing.JMenuItem();
    deleteMenuItem = new javax.swing.JMenuItem();
    headerPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    addButton = new javax.swing.JButton();
    bodyPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    personTableView = new javax.swing.JTable();

    editPersonMenuItem.setText("Edit");
    editPersonMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editPersonMenuItemActionPerformed(evt);
      }
    });
    personTablePopup.add(editPersonMenuItem);

    deleteMenuItem.setText("Delete");
    deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteMenuItemActionPerformed(evt);
      }
    });
    personTablePopup.add(deleteMenuItem);

    headerPanel.setBackground(new java.awt.Color(255, 255, 255));
    headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.lightGray));

    jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel1.setText("Person List");

    addButton.setText("Add");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
    headerPanel.setLayout(headerPanelLayout);
    headerPanelLayout.setHorizontalGroup(
      headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerPanelLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(addButton)
        .addContainerGap())
    );
    headerPanelLayout.setVerticalGroup(
      headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerPanelLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(addButton))
        .addGap(13, 13, 13))
    );

    bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

    personTableView.setAutoCreateRowSorter(true);
    personTableView.setComponentPopupMenu(personTablePopup);
    personTableView.setRowHeight(18);
    personTableView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(personTableView);

    javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
    bodyPanel.setLayout(bodyPanelLayout);
    bodyPanelLayout.setHorizontalGroup(
      bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
    );
    bodyPanelLayout.setVerticalGroup(
      bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bodyPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    controller.onAdd();
  }//GEN-LAST:event_addButtonActionPerformed

  private void editPersonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPersonMenuItemActionPerformed
    controller.onEdit();
  }//GEN-LAST:event_editPersonMenuItemActionPerformed

  private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
    controller.onDelete();
  }//GEN-LAST:event_deleteMenuItemActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JPanel bodyPanel;
  private javax.swing.JMenuItem deleteMenuItem;
  private javax.swing.JMenuItem editPersonMenuItem;
  private javax.swing.JPanel headerPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPopupMenu personTablePopup;
  public javax.swing.JTable personTableView;
  // End of variables declaration//GEN-END:variables
}
